FROM ubuntu:14.04
MAINTAINER CSL R&D <kanishka.dilshan@cslworld.com>
RUN apt-get update
RUN apt-get install python -y
RUN apt-get install python-pip -y
RUN pip install requests
ADD files request.py /
